name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What problem does this solve, or what would you like to do?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?

  - type: dropdown
    id: scope
    attributes:
      label: Area
      options:
        - Sync engine
        - Activity types
        - Asset handling
        - Webhooks
        - Scheduled tasks
        - CLI
        - Admin settings
        - UI/UX
        - Other
